# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vda.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvda.proto\x12\x03vda\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0cVideoRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"4\n\x0eProgressUpdate\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\npercentage\x18\x02 \x01(\x02\x32g\n\x0cVideoService\x12\x1d\n\x04Ping\x12\n.vda.Empty\x1a\t.vda.Pong\x12\x38\n\x0cProcessVideo\x12\x11.vda.VideoRequest\x1a\x13.vda.ProgressUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_PONG']._serialized_start=27
  _globals['_PONG']._serialized_end=50
  _globals['_VIDEOREQUEST']._serialized_start=52
  _globals['_VIDEOREQUEST']._serialized_end=85
  _globals['_PROGRESSUPDATE']._serialized_start=87
  _globals['_PROGRESSUPDATE']._serialized_end=139
  _globals['_VIDEOSERVICE']._serialized_start=141
  _globals['_VIDEOSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
