# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vda.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvda.proto\x12\x03vda\"!\n\x0cVideoRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\"[\n\x0cVideoSegment\x12\x12\n\nstart_time\x18\x01 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x02\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x14\n\x0csegment_type\x18\x04 \x01(\t\"]\n\x0e\x41nalysisResult\x12\x15\n\rtranscription\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12#\n\x08segments\x18\x03 \x03(\x0b\x32\x11.vda.VideoSegment\"q\n\x0eProgressUpdate\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\npercentage\x18\x02 \x01(\x02\x12,\n\nfinal_data\x18\x03 \x01(\x0b\x32\x13.vda.AnalysisResultH\x00\x88\x01\x01\x42\r\n\x0b_final_data\"0\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\x03\"\x1d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t2\x94\x01\n\x0cVideoService\x12\x1d\n\x04Ping\x12\n.vda.Empty\x1a\t.vda.Pong\x12\x38\n\x0cProcessVideo\x12\x11.vda.VideoRequest\x1a\x13.vda.ProgressUpdate0\x01\x12+\n\x04\x43hat\x12\x10.vda.ChatRequest\x1a\x11.vda.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=18
  _globals['_VIDEOREQUEST']._serialized_end=51
  _globals['_EMPTY']._serialized_start=53
  _globals['_EMPTY']._serialized_end=60
  _globals['_PONG']._serialized_start=62
  _globals['_PONG']._serialized_end=85
  _globals['_VIDEOSEGMENT']._serialized_start=87
  _globals['_VIDEOSEGMENT']._serialized_end=178
  _globals['_ANALYSISRESULT']._serialized_start=180
  _globals['_ANALYSISRESULT']._serialized_end=273
  _globals['_PROGRESSUPDATE']._serialized_start=275
  _globals['_PROGRESSUPDATE']._serialized_end=388
  _globals['_CHATREQUEST']._serialized_start=390
  _globals['_CHATREQUEST']._serialized_end=438
  _globals['_CHATRESPONSE']._serialized_start=440
  _globals['_CHATRESPONSE']._serialized_end=469
  _globals['_VIDEOSERVICE']._serialized_start=472
  _globals['_VIDEOSERVICE']._serialized_end=620
# @@protoc_insertion_point(module_scope)
