from pptx import Presentation
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

class GenerationAgent:
    def create_ppt(self, transcript, descriptions, output_path="report.pptx"):
        prs = Presentation()
        
        # Title Slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = "Video Analysis Report"
        slide.placeholders[1].text = "Generated by Intel VDA"

        # Content Slide: Summary
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Transcription Summary"
        slide.placeholders[1].text = transcript[:500] + "..." # Truncate for slide

        # Content Slide: Visual Findings
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Visual Analysis"
        findings = "\n".join([f"- {d}" for d in descriptions[:5]])
        slide.placeholders[1].text = findings

        prs.save(output_path)
        return os.path.abspath(output_path)

    def create_pdf(self, text_content, output_path="summary.pdf"):
        c = canvas.Canvas(output_path, pagesize=letter)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(100, 750, "Intel VDA: Discussion Summary")
        
        c.setFont("Helvetica", 12)
        text_object = c.beginText(100, 700)
        # Simple wrap logic for the PDF
        for line in text_content.split('.'):
            text_object.textLine(line.strip() + '.')
        c.drawText(text_object)
        
        c.save()
        return os.path.abspath(output_path)