import os
from pptx import Presentation
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

class GenerationAgent:
    def create_ppt(self, transcript, chat_history, output_path="video_report.pptx"):
        prs = Presentation()
        
        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = "Video Intelligence Report"
        slide.placeholders[1].text = "Generated by Intel VDA Analyst"

        # Audio summary slide
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Discussion Highlights"
        body = slide.placeholders[1].text_frame
        body.text = transcript[:500] + "..."

        # Chat summary slide
        if chat_history:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Q&A Session Summary"
            slide.placeholders[1].text = chat_history[-1000:] # Last 1k chars only

        full_path = os.path.abspath(output_path)
        prs.save(full_path)
        return full_path

    def create_pdf(self, content, output_path="video_summary.pdf"):
        full_path = os.path.abspath(output_path)
        doc = SimpleDocTemplate(full_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        story.append(Paragraph("Intel VDA: Intelligence Summary", styles['Title']))
        story.append(Spacer(1, 12))

        for section in content.split('\n\n'):
            clean_text = section.replace('\n', '<br/>')
            story.append(Paragraph(clean_text, styles['Normal']))
            story.append(Spacer(1, 12))

        doc.build(story)
        return full_path